// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '???',
    appId: '1:857898637855:web:eecd802b0d44fa5825132a',
    messagingSenderId: '857898637855',
    projectId: 'onwards-448b0',
    authDomain: 'onwards-448b0.firebaseapp.com',
    storageBucket: 'onwards-448b0.firebasestorage.app',
    measurementId: 'G-09GWK5SKGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '???',
    appId: '1:857898637855:web:eecd802b0d44fa5825132a',
    messagingSenderId: '857898637855',
    projectId: 'fir-79444',
    storageBucket: 'fir-79444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '???',
    appId: '1:857898637855:web:eecd802b0d44fa5825132a',
    messagingSenderId: '857898637855',
    projectId: 'fir-79444',
    storageBucket: 'fir-79444.firebasestorage.app',
    iosBundleId: 'com.example.signinExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '???',
    appId: '1:857898637855:web:eecd802b0d44fa5825132a',
    messagingSenderId: '857898637855',
    projectId: 'fir-79444',
    storageBucket: 'fir-79444.firebasestorage.app',
    iosBundleId: 'com.example.signinExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '???',
    appId: '1:857898637855:web:eecd802b0d44fa5825132a',
    messagingSenderId: '857898637855',
    projectId: 'fir-79444',
    authDomain: 'fir-79444.firebaseapp.com',
    storageBucket: 'fir-79444.firebasestorage.app',
    measurementId: 'G-5QVD8Q1PZ7',
  );
}
